### ISSUE TITLE
Create the Study Tips Screen 

### ISSUE THREAD

**Issue by SaulLopezLucas** [CodePath-Pod-24/Fluidity#10]
Users should be able to see study tips arranged in a similar way to the Flix project we completed at the beginning of the program

**Comment by sherrss** [comment]
- Connected to Study Tips View Controller and Study Tip Cell
<img width="337" alt="Screen Shot 2022-10-29 at 4 40 40 PM" src="https://user-images.githubusercontent.com/105692203/198851571-6ed47319-604e-4d15-beae-c8cc89ba3349.png">
