### ISSUE TITLE
Create Home Buttons for Navigation 

### ISSUE THREAD

**Issue by SaulLopezLucas** [CodePath-Pod-24/Fluidity#9]
Create the buttons located at the bottom of the home screen for easy navigation between the different screens

**Comment by sherrss** [comment]
- Tab bar for the study tips page, the home page, and the profile page
- Need to configure the tab bar controller to set the home page as the default page

<img width="337" alt="Screen Shot 2022-10-29 at 4 43 32 PM" src="https://user-images.githubusercontent.com/105692203/198851654-b5c2bc41-4b53-44a6-bcc1-5bb46ac794c3.png">
